languageCode = 'en-us'
title = 'palestickman'
theme = 'archie'
googleAnalytics='G-XY11KS9ZHB'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
[[redirects]]
  from = '/my/**'
  status = 404
  to = '/my/404.html'
[[redirects]]
  from = '/**'
  status = 404
  to = '/404.html'
[params]
  mode = 'toggle'
[languages]
  [languages.my]
    languageCode = 'my'
    languageDirection = 'ltr'
    languageName = 'Myanmar'
    title = 'ခေါင်းစဉ်'
  [languages.en]
    languageCode = 'en'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Project Documentation'
